Repository googleapis/java-spanner-jdbc, pull requests merged in 2020-03, with the labels that each got.

#80 fix: add missing netty-shaded lib for über-jar
  pom.xml
Labels: cla: yes

#78 feat: add support for foreign keys
  src/main/resources/com/google/cloud/spanner/jdbc/DatabaseMetaData_GetCrossReferences.sql
  src/main/resources/com/google/cloud/spanner/jdbc/DatabaseMetaData_GetExportedKeys.sql
  src/main/resources/com/google/cloud/spanner/jdbc/DatabaseMetaData_GetImportedKeys.sql
  src/test/java/com/google/cloud/spanner/jdbc/it/ITJdbcDatabaseMetaDataTest.java
  src/test/resources/com/google/cloud/spanner/jdbc/it/CreateMusicTables.sql
Labels: cla: yes

#81 fix: fix deprecation warnings in JDBC (test) files
  src/main/java/com/google/cloud/spanner/jdbc/AbstractJdbcPreparedStatement.java
  src/main/java/com/google/cloud/spanner/jdbc/JdbcResultSet.java
  src/test/java/com/google/cloud/spanner/jdbc/JdbcAbortedTransactionTest.java
  src/test/java/com/google/cloud/spanner/jdbc/JdbcConnectionTest.java
  src/test/java/com/google/cloud/spanner/jdbc/JdbcGrpcErrorTest.java
  src/test/java/com/google/cloud/spanner/jdbc/JdbcPreparedStatementTest.java
  src/test/java/com/google/cloud/spanner/jdbc/JdbcResultSetTest.java
  src/test/java/com/google/cloud/spanner/jdbc/JdbcStatementTest.java
  src/test/java/com/google/cloud/spanner/jdbc/it/ITJdbcReadOnlyTest.java
  src/test/java/com/google/cloud/spanner/jdbc/it/ITJdbcReadWriteAutocommitTest.java
  src/test/java/com/google/cloud/spanner/jdbc/it/ITJdbcSimpleStatementsTest.java
Labels: cla: yes

#86 tests: unflake max staleness read tests
  src/test/java/com/google/cloud/spanner/jdbc/it/ITJdbcReadOnlyTest.java
  src/test/java/com/google/cloud/spanner/jdbc/it/ITReadOnlySpannerTest.java
  src/test/resources/com/google/cloud/spanner/jdbc/ITReadOnlySpannerTest.sql
Labels: cla: yes

#87 chore: update PR template
  .github/PULL_REQUEST_TEMPLATE.md
  synth.metadata
Labels: automerge, cla: yes

#90 samples: scaffold pom.xml files
  samples/install-without-bom/pom.xml
  samples/pom.xml
  samples/snapshot/pom.xml
  samples/snippets/pom.xml
  synth.metadata
Labels: automerge, cla: yes

#91 samples: fix snippet closing tag
  samples/install-without-bom/pom.xml
Labels: automerge, cla: yes

#76 feat: add support for QueryOptions
  pom.xml
  src/main/java/com/google/cloud/spanner/jdbc/ClientSideStatementValueConverters.java
  src/main/java/com/google/cloud/spanner/jdbc/Connection.java
  src/main/java/com/google/cloud/spanner/jdbc/ConnectionImpl.java
  src/main/java/com/google/cloud/spanner/jdbc/ConnectionOptions.java
  src/main/java/com/google/cloud/spanner/jdbc/ConnectionStatementExecutor.java
  src/main/java/com/google/cloud/spanner/jdbc/ConnectionStatementExecutorImpl.java
  src/main/java/com/google/cloud/spanner/jdbc/JdbcDriver.java
  src/main/java/com/google/cloud/spanner/jdbc/StatementParser.java
  src/main/java/com/google/cloud/spanner/jdbc/StatementResult.java
  src/main/resources/com/google/cloud/spanner/jdbc/ClientSideStatements.json
  src/test/java/com/google/cloud/spanner/jdbc/AbortedTest.java
  src/test/java/com/google/cloud/spanner/jdbc/AbstractConnectionImplTest.java
  src/test/java/com/google/cloud/spanner/jdbc/AbstractMockServerTest.java
  src/test/java/com/google/cloud/spanner/jdbc/ConnectionImplTest.java
  src/test/java/com/google/cloud/spanner/jdbc/ConnectionStatementExecutorTest.java
  src/test/java/com/google/cloud/spanner/jdbc/ConnectionStatementWithNoParametersTest.java
  src/test/java/com/google/cloud/spanner/jdbc/ConnectionStatementWithOneParameterTest.java
  src/test/java/com/google/cloud/spanner/jdbc/ConnectionTest.java
  src/test/java/com/google/cloud/spanner/jdbc/JdbcQueryOptionsTest.java
  src/test/java/com/google/cloud/spanner/jdbc/JdbcTypeConverterTest.java
  src/test/java/com/google/cloud/spanner/jdbc/it/ITJdbcQueryOptionsTest.java
  src/test/java/com/google/cloud/spanner/jdbc/it/ITJdbcSqlScriptTest.java
  src/test/resources/com/google/cloud/spanner/jdbc/ClientSideStatementsTest.sql
  src/test/resources/com/google/cloud/spanner/jdbc/ConnectionImplGeneratedSqlScriptTest.sql
  src/test/resources/com/google/cloud/spanner/jdbc/ITSqlScriptTest_TestQueryOptions.sql
Labels: api: spanner, cla: yes

#92 chore: use java helper for templates
  synth.py
Labels: cla: yes

#98 chore: enable context aware commits
  synth.py
Labels: automerge, cla: yes

#102 chore: update common templates
  .kokoro/build.sh
  .kokoro/common.sh
  .kokoro/dependencies.sh
  .kokoro/linkage-monitor.sh
  renovate.json
  synth.metadata
Labels: automerge, cla: yes

#107 samples: fix samples library versions
  samples/install-without-bom/pom.xml
  samples/snapshot/pom.xml
  samples/snippets/pom.xml
Labels: cla: yes
