Repository googleapis/java-spanner-jdbc, pull requests merged in 2020-12, with the labels that each got.

#285 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: spanner, cla: yes

#255 feat: expose more methods from Connection in JDBC
  clirr-ignored-differences.xml
  src/main/java/com/google/cloud/spanner/jdbc/CloudSpannerJdbcConnection.java
  src/main/java/com/google/cloud/spanner/jdbc/JdbcConnection.java
Labels: api: spanner, cla: yes

#289 chore: Update publish_javadoc.sh
  .kokoro/release/publish_javadoc.sh
  synth.metadata
Labels: api: spanner, automerge, cla: yes, context: full

#292 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: spanner, automerge, cla: yes

#291 feat: report whether column is generated in JDBC metadata
  src/main/resources/com/google/cloud/spanner/jdbc/DatabaseMetaData_GetColumns.sql
  src/test/java/com/google/cloud/spanner/jdbc/it/ITJdbcDatabaseMetaDataTest.java
  src/test/resources/com/google/cloud/spanner/jdbc/it/CreateMusicTables.sql
Labels: api: spanner, cla: yes

#296 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: spanner, automerge, cla: yes

#305 ci(java): ignore bot users for generate-files-bot
  .github/generated-files-bot.yml
  synth.metadata
Labels: api: spanner, automerge, cla: yes, context: full

#306 deps: update spanner to 3.1.2
  pom.xml
Labels: api: spanner, cla: yes

#309 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: spanner, automerge, cla: yes

#284 feat: allow unknown properties in connection url with lenient mode
  src/main/java/com/google/cloud/spanner/jdbc/JdbcDriver.java
  src/test/java/com/google/cloud/spanner/jdbc/JdbcDriverTest.java
Labels: api: spanner, automerge, cla: yes

#311 chore(java): remove formatter action
  .github/workflows/formatting.yaml
  synth.metadata
Labels: api: spanner, automerge, cla: yes, context: full, merge
