Repository googleapis/java-spanner-jdbc, pull requests merged in 2020-10, with the labels that each got.

#231 chore: regenerate common templates
  .github/readme/synth.py
  .github/workflows/samples.yaml
  .kokoro/continuous/readme.cfg
  .kokoro/readme.sh
  synth.metadata
Labels: api: spanner, automerge, cla: yes, context: full

#242 chore: regenerate common templates
  .github/snippet-bot.yml
  .github/workflows/approve-readme.yaml
  .github/workflows/formatting.yaml
  .kokoro/build.sh
  renovate.json
  synth.metadata
Labels: api: spanner, automerge, cla: yes, context: full

#241 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: spanner, automerge, cla: yes

#243 chore: regenerate common templates
  .kokoro/release/publish_javadoc.sh
  CODE_OF_CONDUCT.md
  synth.metadata
Labels: api: spanner, automerge, cla: yes, context: full

#244 chore(ci): fix typo in restrict presubmit samples ITs to only snapshot
  .kokoro/build.sh
  synth.metadata
Labels: automerge, cla: yes, context: full

#246 build: adds api-spanner-java team as owners
  .github/CODEOWNERS
  .repo-metadata.json
Labels: automerge, cla: yes
