Repository googleapis/java-spanner-jdbc, pull requests merged in 2020-11, with the labels that each got.

#248 chore: regenerate common templates
  .github/CODEOWNERS
  .github/generated-files-bot.yml
  synth.metadata
Labels: api: spanner, cla: yes, context: partial

#256 chore(java): use production staging bucket
  .kokoro/release/publish_javadoc.cfg
  synth.metadata
Labels: api: spanner, cla: yes, context: full

#258 deps: use google-cloud-spanner-bom instead of libraries-bom
  pom.xml
Labels: api: spanner, cla: yes

#262 chore: remove unused maven profile
  pom.xml
Labels: api: spanner, cla: yes

#263 docs: add simple connection sample to readme
  README.md
Labels: api: spanner, cla: yes

#264 docs: add package-info to jdbc
  src/main/java/com/google/cloud/spanner/jdbc/package-info.java
Labels: api: spanner, cla: yes

#251 chore(deps): the libraries BOM 15.0.0
  samples/snippets/pom.xml
Labels: api: spanner, cla: yes

#265 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: spanner, automerge, cla: yes

#266 chore(java): ignore return code 28 in README autosynth job
  .kokoro/readme.sh
  synth.metadata
Labels: api: spanner, automerge, cla: yes, context: full

#269 build(java): use code-suggester v1 tag rather than full semver
  .github/workflows/formatting.yaml
  synth.metadata
Labels: api: spanner, automerge, cla: yes, context: full

#274 build(java): use actions/github-script v3 tag rather than full semver
  .github/workflows/approve-readme.yaml
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: api: spanner, automerge, cla: yes, context: full

#277 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: spanner, cla: yes

#279 chore(java): retry staging portion of the release with backoff
  .kokoro/common.sh
  .kokoro/release/stage.sh
  synth.metadata
Labels: api: spanner, automerge, cla: yes, context: full

#278 deps: do not re-declare grpc dependencies as test dependencies
  pom.xml
Labels: api: spanner, cla: yes

#280 build(java): enable blunderbuss for samples
  .github/blunderbuss.yml
  synth.metadata
Labels: api: spanner, automerge, cla: yes, context: full, samples

#281 docs: add connection example to readme
  .readme-partials.yaml
Labels: api: spanner, cla: yes

#282 docs: fix product docs link
  .repo-metadata.json
Labels: api: spanner, cla: yes
