Repository googleapis/java-spanner-jdbc, pull requests merged in 2020-09, with the labels that each got.

#185 feat: add support for NUMERIC type
  src/main/java/com/google/cloud/spanner/jdbc/AbstractJdbcPreparedStatement.java
  src/main/java/com/google/cloud/spanner/jdbc/AbstractJdbcWrapper.java
  src/main/java/com/google/cloud/spanner/jdbc/JdbcDataType.java
  src/main/java/com/google/cloud/spanner/jdbc/JdbcDatabaseMetaData.java
  src/main/java/com/google/cloud/spanner/jdbc/JdbcParameterMetaData.java
  src/main/java/com/google/cloud/spanner/jdbc/JdbcParameterStore.java
  src/main/java/com/google/cloud/spanner/jdbc/JdbcResultSet.java
  src/main/java/com/google/cloud/spanner/jdbc/JdbcResultSetMetaData.java
  src/main/java/com/google/cloud/spanner/jdbc/JdbcTypeConverter.java
  src/main/resources/com/google/cloud/spanner/jdbc/DatabaseMetaData_GetColumns.sql
  src/test/java/com/google/cloud/spanner/jdbc/JdbcArrayTest.java
  src/test/java/com/google/cloud/spanner/jdbc/JdbcDatabaseMetaDataTest.java
  src/test/java/com/google/cloud/spanner/jdbc/JdbcGrpcErrorTest.java
  src/test/java/com/google/cloud/spanner/jdbc/JdbcParameterStoreTest.java
  src/test/java/com/google/cloud/spanner/jdbc/JdbcPreparedStatementTest.java
  src/test/java/com/google/cloud/spanner/jdbc/JdbcTypeConverterTest.java
  src/test/java/com/google/cloud/spanner/jdbc/SpannerJdbcExceptionMatcher.java
  src/test/java/com/google/cloud/spanner/jdbc/it/ITJdbcDatabaseMetaDataTest.java
  src/test/java/com/google/cloud/spanner/jdbc/it/ITJdbcPreparedStatementTest.java
  src/test/resources/com/google/cloud/spanner/jdbc/it/CreateMusicTables.sql
Labels: api: spanner, cla: yes

#197 build(java): switch to release-publish app for notifying GitHub of release status
  .kokoro/release/stage.cfg
  .kokoro/release/stage.sh
  synth.metadata
Labels: api: spanner, cla: yes, context: full

#207 build(ci): enable auto-release for dependency-update-only releases
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: api: spanner, automerge, cla: yes, context: full

#210 chore(java): set yoshi-java as default CODEOWNER
  .github/CODEOWNERS
  synth.metadata
Labels: automerge, cla: yes, context: full

#221 build(java): use yoshi-approver token for auto-approve
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full

#222 chore: add repo settings configuration
  .github/sync-repo-settings.yaml
Labels: api: spanner, automerge, cla: yes

#225 chore(ci): skip autorelease workflow on non-release PRs
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: api: spanner, automerge, cla: yes, context: full

#226 chore(ci): verify autorelease release PR content has changes
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: automerge, cla: yes, context: full
