Repository googleapis/java-spanner-jdbc, pull requests merged in 2021-03, with the labels that each got.

#378 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: spanner, automerge, cla: yes

#365 feat: allow using UUID in PreparedStatement
  src/main/java/com/google/cloud/spanner/jdbc/JdbcParameterStore.java
  src/test/java/com/google/cloud/spanner/jdbc/JdbcParameterStoreTest.java
  src/test/java/com/google/cloud/spanner/jdbc/JdbcPreparedStatementTest.java
  src/test/java/com/google/cloud/spanner/jdbc/it/ITJdbcPreparedStatementTest.java
Labels: api: spanner, cla: yes

#381 chore: remove docLava v2 doc generation
  .kokoro/release/publish_javadoc.cfg
  .kokoro/release/publish_javadoc.sh
  synth.metadata
Labels: api: spanner, automerge, cla: yes, context: full

#382 chore: copy README to docfx-yml dir
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: spanner, automerge, cla: yes, context: full

#261 feat: add support for CommitStats
  clirr-ignored-differences.xml
  src/main/java/com/google/cloud/spanner/jdbc/CloudSpannerJdbcConnection.java
  src/main/java/com/google/cloud/spanner/jdbc/JdbcConnection.java
  src/test/java/com/google/cloud/spanner/jdbc/JdbcCommitStatsTest.java
  src/test/java/com/google/cloud/spanner/jdbc/JdbcConnectionTest.java
Labels: api: spanner, cla: yes

#389 build(java): update autorelease title check in response to the new multi release branch changes
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: api: spanner, automerge, cla: yes, context: full

#391 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: spanner, automerge, cla: yes

#388 perf: use PLAN mode to get result metadata
  src/main/java/com/google/cloud/spanner/jdbc/AbstractJdbcPreparedStatement.java
  src/main/java/com/google/cloud/spanner/jdbc/AbstractJdbcStatement.java
  src/main/java/com/google/cloud/spanner/jdbc/JdbcPreparedStatement.java
  src/test/java/com/google/cloud/spanner/jdbc/JdbcPreparedStatementTest.java
  src/test/java/com/google/cloud/spanner/jdbc/it/ITJdbcPreparedStatementTest.java
Labels: api: spanner, cla: yes

#400 build: remove java7 as required check
  .github/sync-repo-settings.yaml
Labels: api: spanner, cla: yes

#404 docs: add reference to jar-with-dependencies in readme
  .readme-partials.yaml
Labels: api: spanner, cla: yes

#405 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: spanner, automerge, cla: yes

#412 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: spanner, automerge, cla: yes

#411 chore: sets the min version of the repo as Java 8
  .repo-metadata.json
Labels: api: spanner, cla: yes

#413 chore: marks the branch 1.21.x as stable
  .github/release-please.yml
  .github/sync-repo-settings.yaml
Labels: api: spanner, cla: yes

#414 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: spanner, automerge, cla: yes
