Repository googleapis/java-spanner-jdbc, pull requests merged in 2021-04, with the labels that each got.

#417 chore: Re-generated to pick up changes from synthtool
  .github/release-please.yml
  .kokoro/build.sh
  .kokoro/nightly/java7.cfg
  .kokoro/presubmit/java7.cfg
  .kokoro/release/publish_javadoc.sh
  synth.metadata
Labels: api: spanner, cla: yes, context: partial

#424 build(java): skip javadoc tests during dependencies test
  .kokoro/dependencies.sh
  synth.metadata
Labels: api: spanner, cla: yes, context: full

#416 chore: autosynth
  synth.metadata
Labels: api: spanner, cla: yes, context: none

#428 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: spanner, cla: yes

#431 fix: typo
  .kokoro/build.sh
  synth.metadata
Labels: api: spanner, automerge, cla: yes, context: full

#434 fix: release scripts from issuing overlapping phases
  .kokoro/release/snapshot.sh
  .kokoro/release/stage.sh
  synth.metadata
Labels: api: spanner, cla: yes, context: full

#437 chore: marks branch 1.21.x as stable
  .github/release-please.yml
  .github/sync-repo-settings.yaml
  synth.py
Labels: api: spanner, cla: yes

#435 chore: add default assignee for issues
  .github/blunderbuss.yml
  synth.py
Labels: api: spanner, cla: yes

#445 fix: NPE was thrown when getting an array of structs from a ResultSet
  src/main/java/com/google/cloud/spanner/jdbc/JdbcDataType.java
  src/test/java/com/google/cloud/spanner/jdbc/JdbcArrayTest.java
  src/test/java/com/google/cloud/spanner/jdbc/it/ITJdbcSimpleStatementsTest.java
Labels: api: spanner, cla: yes

#450 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: spanner, automerge, cla: yes
