Repository googleapis/java-spanner-jdbc, pull requests merged in 2021-02, with the labels that each got.

#341 chore: Re-generated to pick up changes from synthtool.
  .github/workflows/ci.yaml
  .kokoro/linkage-monitor.sh
  .kokoro/release/publish_javadoc.cfg
  .kokoro/release/publish_javadoc11.cfg
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: spanner, cla: yes, context: partial

#345 build(java): update autorelease branch name check
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: api: spanner, automerge, cla: yes, context: full

#346 chore: Re-generated to pick up changes from synthtool.
  .kokoro/release/publish_javadoc11.cfg
  LICENSE
  synth.metadata
Labels: automerge, cla: yes, context: full

#326 feat: Support Array conversion to ResultSet
  src/main/java/com/google/cloud/spanner/jdbc/JdbcArray.java
  src/test/java/com/google/cloud/spanner/jdbc/JdbcArrayTest.java
Labels: api: spanner, cla: yes

#343 docs: fix javadoc formatting
  src/main/java/com/google/cloud/spanner/jdbc/JdbcDriver.java
Labels: api: spanner, cla: yes

#347 Fix: Return entire stack trace for deadline exceeded error
  src/main/java/com/google/cloud/spanner/jdbc/JdbcSqlExceptionFactory.java
Labels: api: spanner, cla: yes

#348 test: re-enable JDBC converter test
  src/test/java/com/google/cloud/spanner/jdbc/JdbcTypeConverterTest.java
Labels: api: spanner, cla: yes, type: cleanup

#350 build(java): update autorelease script
  .github/workflows/auto-release.yaml
  synth.metadata
Labels: api: spanner, automerge, cla: yes, context: full

#356 ci: linkage monitor CI job to use build.sh
  .github/workflows/ci.yaml
  synth.metadata
Labels: api: spanner, automerge, cla: yes, context: full

#358 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: spanner, automerge, cla: yes

#360 chore: update cloud-rad buckets
  .kokoro/release/publish_javadoc.cfg
  .kokoro/release/publish_javadoc.sh
  .kokoro/release/publish_javadoc11.cfg
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: spanner, cla: yes, context: full

#335 feat: allow setting min/max sessions
  src/main/java/com/google/cloud/spanner/jdbc/JdbcDriver.java
  src/test/java/com/google/cloud/spanner/jdbc/JdbcConnectionUrlTest.java
  src/test/java/com/google/cloud/spanner/jdbc/JdbcGrpcErrorTest.java
Labels: api: spanner, cla: yes

#361 build: skip Maven download logs
  .kokoro/build.sh
  synth.metadata
Labels: api: spanner, automerge, cla: yes, context: full

#362 build: reduce download junk in log files
  .kokoro/build.sh
  .kokoro/dependencies.sh
  synth.metadata
Labels: api: spanner, automerge, cla: yes, context: full

#370 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: spanner, automerge, cla: yes
