Repository googleapis/java-spanner-jdbc, pull requests merged in 2021-12, with the labels that each got.

#691 chore: make owlbot check required
  .github/sync-repo-settings.yaml
Labels: api: spanner, automerge

#682 chore: auto-assign issues to new repo owner
  .github/blunderbuss.yml
Labels: cla: yes, api: spanner

#694 deps: bump google-cloud-spanner to 6.17.3 and opencensus to 0.30.0
  pom.xml
Labels: api: spanner

#697 chore: add enumeration type of library
  .repo-metadata.json
Labels: api: spanner, automerge
