Repository googleapis/java-spanner-jdbc, pull requests merged in 2021-09, with the labels that each got.

#594 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: cla: yes, api: spanner, automerge

#598 chore(java): install maven 3.8.1 at runtime
  .github/workflows/ci.yaml
  synth.metadata
Labels: cla: yes, api: spanner, automerge, context: full

#599 chore: setup maven 3.8.1 for ci tasks
  .github/workflows/ci.yaml
  .github/workflows/integration-tests-against-emulator.yaml
  .github/workflows/samples.yaml
Labels: cla: yes, api: spanner

#604 chore: remove readme autosynth config
  .github/readme/synth.metadata/synth.metadata
  .github/readme/synth.py
  .kokoro/continuous/readme.cfg
Labels: cla: yes, api: spanner, automerge

#611 chore: re-generated to pick up changes from self
  .github/workflows/ci.yaml
  synth.metadata
Labels: cla: yes, api: spanner, context: none

#616 test: remove the category from the base class for all integration tests
  src/test/java/com/google/cloud/spanner/jdbc/ITAbstractJdbcTest.java
Labels: cla: yes, api: spanner

#624 build: configure release-please should tag releases
  .github/release-please.yml
Labels: cla: yes, api: spanner, automerge

#628 chore: change branch master to main in github configurations
  .github/blunderbuss.yml
  .github/sync-repo-settings.yaml
  .github/workflows/integration-tests-against-emulator.yaml
  README.md
Labels: cla: yes, api: spanner, automerge
