Repository googleapis/java-spanner-jdbc, pull requests merged in 2021-05, with the labels that each got.

#454 feat: allow get/set Spanner Value instances
  src/main/java/com/google/cloud/spanner/jdbc/AbstractJdbcPreparedStatement.java
  src/main/java/com/google/cloud/spanner/jdbc/JdbcParameterStore.java
  src/main/java/com/google/cloud/spanner/jdbc/JdbcPreparedStatement.java
  src/main/java/com/google/cloud/spanner/jdbc/JdbcTypeConverter.java
  src/test/java/com/google/cloud/spanner/jdbc/JdbcParameterStoreTest.java
  src/test/java/com/google/cloud/spanner/jdbc/JdbcPreparedStatementTest.java
  src/test/java/com/google/cloud/spanner/jdbc/JdbcResultSetTest.java
  src/test/java/com/google/cloud/spanner/jdbc/it/ITJdbcPreparedStatementTest.java
Labels: api: spanner, automerge, cla: yes

#458 chore: remove unused statements file
  src/main/resources/com/google/cloud/spanner/jdbc/ClientSideStatements.json
Labels: api: spanner, cla: yes

#461 chore: adding cloud-rad java xrefs
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: spanner, cla: yes, context: full

#465 build(java): remove codecov action
  .github/workflows/ci.yaml
  synth.metadata
Labels: api: spanner, automerge, cla: yes, context: full

#467 chore: add changelog to cloud-rad
  .kokoro/release/publish_javadoc11.sh
  synth.metadata
Labels: api: spanner, automerge, cla: yes, context: full

#468 tests: fixes jdbc query options test
  src/test/java/com/google/cloud/spanner/jdbc/JdbcQueryOptionsTest.java
Labels: api: spanner, cla: yes

#469 tests: fixes sql script test
  src/test/java/com/google/cloud/spanner/jdbc/it/ITJdbcSqlScriptTest.java
Labels: api: spanner, cla: yes

#474 feat: add `gcf-owl-bot[bot]` to `ignoreAuthors`
  .github/generated-files-bot.yml
  synth.metadata
Labels: api: spanner, automerge, cla: yes, context: full

#472 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: spanner, automerge, cla: yes

#477 chore: dump maven version along with java
  .kokoro/build.sh
  synth.metadata
Labels: api: spanner, automerge, cla: yes, context: full

#478 docs: document connection properties in README
  .readme-partials.yaml
  src/main/java/com/google/cloud/spanner/jdbc/JdbcDriver.java
Labels: api: spanner, cla: yes

#481 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: spanner, automerge, cla: yes
