Repository googleapis/java-spanner-jdbc, pull requests merged in 2021-06, with the labels that each got.

#489 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: spanner, automerge, cla: yes

#495 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: spanner, automerge, cla: yes

#498 deps: update dependency com.google.cloud:google-cloud-spanner-bom to v6.6.0
  pom.xml
  src/test/java/com/google/cloud/spanner/jdbc/JdbcQueryOptionsTest.java
  src/test/java/com/google/cloud/spanner/jdbc/it/ITJdbcQueryOptionsTest.java
Labels: api: spanner, cla: yes

#505 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: spanner, automerge, cla: yes

#506 fix: Update dependencies.sh to not break on mac
  .kokoro/dependencies.sh
  synth.metadata
Labels: api: spanner, automerge, cla: yes, context: full

#510 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: spanner, automerge, cla: yes

#511 fix: prevent relocating urls that start with com like /computeMetadata/
  pom.xml
Labels: api: spanner, automerge, cla: yes

#512 chore: minimize noise from build scripts
  .kokoro/coerce_logs.sh
  synth.metadata
Labels: api: spanner, automerge, cla: yes, context: full

#514 fix: Add `shopt -s nullglob` to dependencies script
  .kokoro/dependencies.sh
  synth.metadata
Labels: api: spanner, automerge, cla: yes, context: full
