Repository googleapis/java-spanner-jdbc, pull requests merged in 2021-07, with the labels that each got.

#523 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: spanner, automerge, cla: yes

#528 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: spanner, automerge, cla: yes

#530 chore: remove distributionManagement section
  pom.xml
Labels: api: spanner, automerge, cla: yes

#531 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: spanner, automerge, cla: yes

#533 chore: remove All rights reserved clause from java.header
  java.header
  synth.metadata
Labels: api: spanner, automerge, cla: yes, context: full

#270 feat: add support for tagging to JDBC connection
  clirr-ignored-differences.xml
  src/main/java/com/google/cloud/spanner/jdbc/CloudSpannerJdbcConnection.java
  src/main/java/com/google/cloud/spanner/jdbc/JdbcConnection.java
Labels: api: spanner, cla: yes

#535 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: spanner, automerge, cla: yes

#536 chore: add dependencyDashboardLabels to renovate.json
  renovate.json
  synth.metadata
Labels: api: spanner, automerge, cla: yes, context: full

#542 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: spanner, automerge, cla: yes
