Repository googleapis/java-spanner-jdbc, pull requests merged in 2021-01, with the labels that each got.

#315 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: spanner, automerge, cla: yes

#323 fix: getting resultset metadata twice could skip row
  src/main/java/com/google/cloud/spanner/jdbc/JdbcResultSet.java
  src/test/java/com/google/cloud/spanner/jdbc/JdbcResultSetTest.java
Labels: api: spanner, cla: yes

#324 feat: support default ClientInfo properties
  src/main/java/com/google/cloud/spanner/jdbc/AbstractJdbcConnection.java
  src/main/java/com/google/cloud/spanner/jdbc/JdbcConnection.java
  src/main/java/com/google/cloud/spanner/jdbc/JdbcDatabaseMetaData.java
  src/test/java/com/google/cloud/spanner/jdbc/JdbcConnectionGeneratedSqlScriptTest.java
  src/test/java/com/google/cloud/spanner/jdbc/JdbcConnectionTest.java
  src/test/java/com/google/cloud/spanner/jdbc/JdbcDatabaseMetaDataTest.java
Labels: api: spanner, cla: yes

#330 chore: adding docfx doclet resource
  .kokoro/release/publish_javadoc.cfg
  synth.metadata
Labels: api: spanner, automerge, cla: yes, context: full

#336 build: migrate to flakybot
  .kokoro/build.sh
Labels: api: spanner, automerge, cla: yes

#333 feat: support creating shaded jars
  .readme-partials.yaml
  pom.xml
Labels: api: spanner, cla: yes

#337 chore: regenerate README
  .github/readme/synth.metadata/synth.metadata
  README.md
Labels: api: spanner, automerge, cla: yes
