Repository googleapis/java-spanner-jdbc, pull requests merged in 2022-11, with the labels that each got.

#1025 chore: remove native-maven-plugin 0.9.14 workaround
  .kokoro/build.sh
  pom.xml
Labels: api: spanner, size: m

#1050 chore: correct spanner project reference for ITs
  .kokoro/nightly/integration.cfg
Labels: api: spanner, size: xs

#1052 chore: edit scope of gax dep from test to runtime
  pom.xml
Labels: api: spanner, automerge, size: s

#936 feat: add tests for DML with Returning clause
  src/main/java/com/google/cloud/spanner/jdbc/JdbcStatement.java
  src/test/java/com/google/cloud/spanner/jdbc/JdbcStatementTest.java
  src/test/java/com/google/cloud/spanner/jdbc/it/ITJdbcPreparedStatementTest.java
Labels: api: spanner, automerge, size: m
