Repository googleapis/java-spanner-jdbc, pull requests merged in 2022-05, with the labels that each got.

#871 fix: executeBatch did not respect statement timeout
  pom.xml
  src/main/java/com/google/cloud/spanner/jdbc/AbstractJdbcStatement.java
  src/main/java/com/google/cloud/spanner/jdbc/JdbcStatement.java
  src/test/java/com/google/cloud/spanner/jdbc/JdbcStatementTimeoutTest.java
Labels: api: spanner, size: m

#877 chore: change repo maintainer
  .github/blunderbuss.yml
Labels: kokoro:run, api: spanner, size: xs

#887 deps: google-cloud-spanner-bom 6.25.5
  pom.xml
Labels: api: spanner, automerge, size: xs
